#!/usr/bin/env python3
"""Sync the frozen, read-only copy of `xz-seek` at vendor/xz-seek/.

This repo depends on `xz-seek` (docs/design/architecture.md, "The compressed
source") before that crate is published: this repo is its first
real-world consumer, and the interface is vetted by being used rather than
frozen into a version and discovered. A path dependency onto the sibling
working tree was rejected there -- it breaks `cargo check` on any checkout
lacking that tree, even behind an off-by-default feature, because the
dependency graph resolves before features are considered. So the copy is
committed, and this script is the
transformation, run again whenever the source moves and re-synced rather than
hand-merged.

What it keeps: `src/`, the two license files, and a *trimmed* `Cargo.toml`.
What it drops: `tests/`, `fixtures/`, and the manifest's `[workspace]`,
`[profile.dev]`, `[profile.profiling]` and `[dev-dependencies]` tables -- none
of it resolves once the crate is dropped into another workspace, and the
profile tables are silently ignored (with a warning) for a non-root package
regardless. `[package]`, `[features]`, `[lints.rust]` and `[dependencies]`
pass through untouched, comments included, because this is a transformation
of the source, not a rewrite of it -- a bug found in the copy goes upstream
and returns at the next sync; it is never patched in place here.

The extraction reads from `git archive HEAD` in the source repo, not from its
working tree: that tree may carry unrelated uncommitted work (its own, or a
session in progress), and only the committed state is fit to vendor.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEST = REPO / "vendor" / "xz-seek"

# This machine's xz-seek checkout (CLAUDE.local.md, "xz-seek (external crate,
# vendored into this repo)"). A different machine points this elsewhere.
SOURCE = Path(
    os.environ.get("PGDQ_XZ_SEEK_SOURCE", "/mnt/wd12t/fedora/experiments/xz-seek")
)

# Top-level manifest tables, and which side of the cut each falls on. Any
# table found in the source manifest that names neither list is a manifest
# shape this script has not seen -- fail rather than guess.
KEEP_TABLES = {"package", "features", "lints.rust", "dependencies"}
DROP_TABLES = {"workspace", "profile.dev", "profile.profiling", "dev-dependencies"}

HEADER_RE = re.compile(r"^\[([A-Za-z0-9_.-]+)\]\s*$")


def _run(cmd: list[str], cwd: Path | None = None) -> str:
    return subprocess.run(
        cmd, cwd=cwd, check=True, capture_output=True, text=True
    ).stdout


def transform_manifest(text: str) -> str:
    lines = text.splitlines(keepends=True)
    headers: list[tuple[str, int]] = []
    for i, line in enumerate(lines):
        m = HEADER_RE.match(line)
        if m:
            headers.append((m.group(1), i))

    unknown = {name for name, _ in headers} - KEEP_TABLES - DROP_TABLES
    if unknown:
        raise SystemExit(
            f"vendor_xz_seek: xz-seek's Cargo.toml has table(s) this script "
            f"doesn't know how to place: {sorted(unknown)}. Add them to "
            f"KEEP_TABLES or DROP_TABLES in this script before re-syncing."
        )

    # A table's block starts at its header, minus any contiguous run of
    # comment lines directly above it (those describe the table that
    # follows), and runs up to the next table's block start.
    block_starts = []
    for _, header_idx in headers:
        start = header_idx
        while start > 0 and lines[start - 1].lstrip().startswith("#"):
            start -= 1
        block_starts.append(start)

    kept_chunks = []
    for idx, (name, header_idx) in enumerate(headers):
        block_start = block_starts[idx]
        block_end = block_starts[idx + 1] if idx + 1 < len(headers) else len(lines)
        if name in KEEP_TABLES:
            kept_chunks.append("".join(lines[block_start:block_end]))

    banner = (
        "# Vendored, read-only. Generated by "
        "`scripts/vendor_xz_seek.py` from xz-seek's own Cargo.toml --\n"
        "# do not hand-edit; re-run that script instead. A trimmed manifest:\n"
        "# `[workspace]`, `[profile.dev]`, `[profile.profiling]` and\n"
        "# `[dev-dependencies]` removed, since none of them resolve once this\n"
        "# crate is dropped into another workspace.\n\n"
    )
    return banner + "".join(kept_chunks)


def main() -> None:
    if not (SOURCE / ".git").exists():
        raise SystemExit(f"vendor_xz_seek: {SOURCE} is not a git checkout")

    commit = _run(["git", "rev-parse", "HEAD"], cwd=SOURCE).strip()
    commit_date = _run(
        ["git", "show", "-s", "--format=%cI", commit], cwd=SOURCE
    ).strip()

    for path in ("src", "Cargo.toml", "LICENSE-MIT", "LICENSE-APACHE"):
        rc = subprocess.run(
            ["git", "cat-file", "-e", f"{commit}:{path}"],
            cwd=SOURCE,
            capture_output=True,
        )
        if rc.returncode != 0:
            raise SystemExit(
                f"vendor_xz_seek: {path} not found at {SOURCE}@{commit[:12]}"
            )

    with tempfile.TemporaryDirectory() as tmp_str:
        tmp = Path(tmp_str)
        archive_path = tmp / "xz-seek.tar"
        with open(archive_path, "wb") as f:
            subprocess.run(
                [
                    "git",
                    "archive",
                    commit,
                    "--",
                    "src",
                    "Cargo.toml",
                    "LICENSE-MIT",
                    "LICENSE-APACHE",
                ],
                cwd=SOURCE,
                check=True,
                stdout=f,
            )
        extracted = tmp / "extracted"
        extracted.mkdir()
        with tarfile.open(archive_path) as tar:
            tar.extractall(extracted, filter="data")

        manifest_src = (extracted / "Cargo.toml").read_text()
        manifest_out = transform_manifest(manifest_src)

        if DEST.exists():
            shutil.rmtree(DEST)
        DEST.mkdir(parents=True)
        shutil.copytree(extracted / "src", DEST / "src")
        shutil.copy2(extracted / "LICENSE-MIT", DEST / "LICENSE-MIT")
        shutil.copy2(extracted / "LICENSE-APACHE", DEST / "LICENSE-APACHE")
        (DEST / "Cargo.toml").write_text(manifest_out)

    stamp = f"""\
Vendored from {SOURCE}
commit {commit}
committed {commit_date}

This is a read-only snapshot, not a fork: a bug found here is fixed upstream
and arrives at the next sync, never patched in this copy directly. Re-sync
with `cd scripts && uv run vendor_xz_seek.py`.

`pgdump_query` names this copy as a path dependency (see
docs/design/architecture.md, "The compressed source"), and re-takes it as
upstream moves rather than waiting for a consumer that needs the newer work.
So a sync can bring in code nothing in this tree exercises: it is finished by
`cargo check --workspace` and `cargo test --workspace`, not by this script.
"""
    (DEST / "VENDORED_FROM").write_text(stamp)

    print(f"vendored xz-seek@{commit[:12]} ({commit_date}) into {DEST}")


if __name__ == "__main__":
    main()
